### ISSUE TITLE
A network issue has occurred. 

### ISSUE THREAD

**Issue by yochananmarqos** [gi-lom/dialect#102]
The text translation works, but there's an issue with voice dictation. This occurs with `gTTS` 2.1.1 + `gTTS-token` 1.1.3 and `gTTS` 2.1.2 / 2.2.0 / 2.2.1 + `gTTS-token` 1.1.4. 

I'm using `dialect-git` 1.1.0.r12.gff51505 on Manjaro GNOME (unstable branch).

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/dialect/dialect/window.py", line 160, in load_lang_speech
    self.lang_speech = list(lang.tts_langs(tld='com').keys())
TypeError: tts_langs() got an unexpected keyword argument 'tld'
```

**Comment by fushinari** [comment]
Works fine for me with gTTS 2.1.2 and gTTS-token 1.1.4. But I'll look into it.

**Comment by fushinari** [comment]
Could you test it now? This should fix what your log indicates to be the issue.

That said, gTTS is still a hit-or-miss sadly.

**Comment by yochananmarqos** [comment]
Yes, that commit fixed it. Thanks!
