### ISSUE TITLE
Flatpak Issues

### ISSUE THREAD

**Issue by kb8cb40j1av39c02** [gi-lom/dialect#103]
I am using Pop!_OS 20.04 with all the latest updates. The Flatpak version of the app does not seem to respect the Desktop Theme (other Flatpak apps all do - idk why this one does not). Also - the dark mode toggle does not change anything for me.

Thanks for the handy app though - it's very useful :)!

**Comment by rafaelmardojai** [comment]
Mmh, very strange. We're not doing anything non-standard here.

We will need to investigate further. Sadly I don't have time to try to reproduce it now. I remember @fushinari tested Dialect with Yaru theme on Ubuntu, but I don't know if he was using the Flatpak.

**Comment by fushinari** [comment]
I only tested with the Yaru 20.10 theme on Arch and it was not on Flatpak.

Custom theming (or distro theming as in this case) is often a hit or miss in Flatpak. Will need to test, but I don't have a Pop!_OS setup right now to test with and limited internet access right now.

That said, @rafaelmardojai is right. We don't do anything non-standard here afaik... This is most probably a Flatpak bug or a distro bug.

But then, the dark theme issue should not be happening. So, I'm not sure yet.

@kb8cb40j1av39c02 does running it from the terminal produce any output?

**Comment by fushinari** [comment]
Also, just to confirm, could you additionally send the output of `flatpak list | grep org.gtk.Gtk3theme`?

**Comment by rafaelmardojai** [comment]
I installed Pop!_OS gtk theme on my Fedora and also `org.gtk.Gtk3theme.Pop` from flathub. Everything worked as expected. 

![Peek 30-11-2020 16-22](https://user-images.githubusercontent.com/6210397/100668303-b9464d00-3329-11eb-84da-9d1945c94994.gif)

It actually looks cool.

**Comment by fushinari** [comment]
Yeah, I can't replicate it on Arch either. Might be an issue specific to Pop!_OS.

**Comment by kb8cb40j1av39c02** [comment]
Sorry replying late - i did some further investigations:
The Pop-Light and Pop-Dark Theme work without issues. It's when switching to third-party themes like the popular Materia Light/Dark or Mac OS like Themes where Dialect defaults to the default Yaru theme. Other flatpak applications that I have installed like Remmina still adapt the third-party Theme.

**Comment by fushinari** [comment]
Ah, then everything works as intended. Dialect is only supposed to work with themes that also have Flatpak variants. Otherwise, it will fallback to the default theme. Adapting to a third-party theme that has no flatpak variant is a bug. Thanks for replying and glad to hear you like the application. :)
