### ISSUE TITLE
Network Failure on all translations

### ISSUE THREAD

**Issue by joshbowyer** [gi-lom/dialect#104]
Any time I try to translate something, even when I specify the origin language, I get a network error and nothing happens. This started happening suddenly and without any change on my side. I think I read that this may be an upstream issue with py-googletrans but I didnt see any issues in that git project that matched this exactly.

**Comment by fushinari** [comment]
Yes, py-googletrans is broken for most people now. Relevant issue: https://github.com/ssut/py-googletrans/issues/48

I'm not sure about the next step because DeepL has kinda geo-blocked me from contacting them. Whatever I ask, a bot replies saying DeepL Pro isn't available in my country. So, that may not be a good choice yet.

We might just have to wait for a fix.

**Comment by rafaelmardojai** [comment]
Updating to the new [py-googletrans alpha](https://pypi.org/project/googletrans/3.1.0a0/) fixed the issue for me, I'm going to update the Flatpak.

**Comment by rafaelmardojai** [comment]
@fushinari I have updated the py-googletrans version, could you test if everything works fine?

**Comment by fushinari** [comment]
Can confirm. It seems to be fixed now :+1:

**Comment by fushinari** [comment]
@rafaelmardojai think we should keep this open till next release?

@joshbowyer you can test this right away by downloading the [CI build](https://github.com/gi-lom/dialect/suites/1622746360/artifacts/29832636), extracting and installing the resulting `*.flatpak` file.

**Comment by rafaelmardojai** [comment]
@fushinari Yes, and we should release very soon. This should also fix #95 right?

**Comment by fushinari** [comment]
Yes, it does for me.

**Comment by rafaelmardojai** [comment]
Nice. If you have time go ahead and release! `1.2.0` or `1.1.1`?

**Comment by fushinari** [comment]
We do have some new strings, like the "Keyboard Shortcuts" and the changelog. Should we call on translators?

**Comment by rafaelmardojai** [comment]
Yeah, it's mainly a bugfix release.

If we consider it a "emergency update" we can deliver with brocken translations, maybe only update the .po files to the changes.

**Comment by fushinari** [comment]
1.1.1 is out. Closing this. :)
