### ISSUE TITLE
Argos Translate Backend

### ISSUE THREAD

**Issue by jannuary** [gi-lom/dialect#112]
[Argos Translate](https://github.com/argosopentech/argos-translate) is an offline translation app/library written in Python. 

It would be great to have that as an option instead of sending everything through Google.

**Comment by rugk** [comment]
Aka https://translate.astian.org/. There you would have a nice API endpoint for that.

**Comment by fossdd** [comment]
[Argos Translate](https://github.com/argosopentech/argos-translate) is a "library" used by [LibreTranslate](https://github.com/uav4geo/LibreTranslate).

[`https://translate.astian.org/`](https://translate.astian.org/) and [`https://libretranslate.com/`](https://libretranslate.com/) are instances of LibreTranslate.

LibreTranslate has a great, simple API. [See docs](https://libretranslate.com/docs)
