### ISSUE TITLE
Better appdata summary

### ISSUE THREAD

**Issue by bertob** [gi-lom/dialect#113]
The current summary "A translation app for GNOME" isn't great, because it mentions the target environment (imagine every iOS app mentioning that it targets iOS in the summary :D). It's fine to mention GNOME in the description, but the summary should be short and focus on what it can do for people, e.g. "Translate any language".

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by rafaelmardojai** [comment]
`A translation app for GNOME` was an improvement from `A translation app for GTK environments based on Google Translate`, but I agree that it can be improved a little bit more.

`Translate any language` sounds good, but I'm not totally convinced.

**Comment by fushinari** [comment]
How about `Translate any text from one language to another`?

**Comment by bertob** [comment]
> How about Translate any text from one language to another?

Too long, you want something that fits onto an app tile without ellipsizing:

![image](https://user-images.githubusercontent.com/1908896/104168395-4a671400-53fe-11eb-93f7-4c0455d13a1f.png)

**Comment by fushinari** [comment]
I feel like "Translate any language" is wrong because what we're translating is the text rather than the language. So, how about "Translate text between languages" instead?

**Comment by bertob** [comment]
I think you could cut the "text" and do "Translate between languages".

**Comment by fushinari** [comment]
Okay, sounds good. What do you think, @rafaelmardojai ?

**Comment by rafaelmardojai** [comment]
What about `Translate between many languages`?   

> I feel like "Translate any language" is wrong because what we're translating is the text rather than the language

I'm not a English expert, but I think that it works fine in that context. For example I can say "I can translate any language", meaning that I can translate any text in any language.

**Comment by rafaelmardojai** [comment]
Sorry, I had a electrical power outage when I was answering, and now I just sent the saved draft. 

Yeah, `Translate between languages` sounds good for me.
