### ISSUE TITLE
Allow live translation without clicking on the "translate" icon 

### ISSUE THREAD

**Issue by jbpichancourt** [gi-lom/dialect#121]
Hi there. Thx for your awesome app. Much appreciated.
Would be great to allow live translation without clicking on the "translate" icon, like what is done on google translate
thx and keep up the good work

**Comment by fushinari** [comment]
Live translation is a feature that can be enabled in Preferences.

**Comment by jbpichancourt** [comment]
my bad sorry. just erase my post

**Comment by fushinari** [comment]
No worries :) It happens.
