### ISSUE TITLE
Update translations for 1.2.0

### ISSUE THREAD

**Issue by rafaelmardojai** [gi-lom/dialect#124]
We're going to release `1.2.0` soon, if you have time to update the translations we will be very grateful.

Thanks in advance!

- [x] German @Etamuk
- [x] Spanish @rafaelmardojai 
- [x] Persian @musicsd
- [x] Hungarian @meskobalazs
- [x] Indonesian @cho2
- [x] Italian @albanobattistella
- [x] Dutch @Vistaus
- [x] Brazilian Portuguese @xfgusta
- [x] Russian @nexeleriot
- [x] Swedish @eson57
- [x] Turkish @v30xy

**Comment by Etamuk** [comment]
Thanks for that information. I will update my translation (German) tomorrow in the early afternoon. 
I hope that´s ok for the release date :-)

**Comment by rafaelmardojai** [comment]
@Etamuk No problem, we don't have release date, so we can wait.

**Comment by v30xy** [comment]
Done. Waiting for merge :)

**Comment by Etamuk** [comment]
Short question: can you please explain the meaning of "Translate between languages"?

**Comment by fushinari** [comment]
> Short question: can you please explain the meaning of "Translate between languages"?

"Translate between languages" as in a shortened form of "Translate from one language to another". Any approximate translation that's roughly 30 characters or less is fine.

**Comment by Etamuk** [comment]
> a shortened form of "Translate from one language to another". Any approximate translation that's roughly 30 characters or less is fine.

Thank you!

**Comment by fushinari** [comment]
> Thank you!

**Comment by fushinari** [comment]
@musicsd Sorry, I don't mean to rush you but any updates on the progress of the Persian translation? Taking your time is fine, since we don't have a strict release schedule, but some communication would be appreciated :)

**Comment by musicsd** [comment]
I'm sorry, I did not have time to do this. The translation will be completed soon.

**Comment by musicsd** [comment]
Dialect has also been added to the [Guix wishlist](https://libreplanet.org/wiki/Group:Guix/Wishlist), and Guix developers and I will try to package Dialect for the Guix System as soon as possible.

**Comment by fushinari** [comment]
> I'm sorry, I did not have time to do this. The translation will be completed soon.

Thanks for letting me know! It's fine, take your time. I just wanted to know the status. (Sorry if I sounded rude or something, English is not my first language :sweat_smile: )

> Dialect has also been added to the Guix wishlist, and Guix developers and I will try to package Dialect for the Guix System as soon as possible.

Thank you! I've always liked the Guix package manager, so it's great to know that Dialect may soon be installable through it. Once it becomes installable, please send in a PR or open an issue so that we can add installation instructions to the README. :)

**Comment by fushinari** [comment]
I think we're ready for 1.2.0 now? Anything pending or any bugs to fix?

**Comment by rafaelmardojai** [comment]
> I think we're ready for 1.2.0 now? Anything pending or any bugs to fix?

Nothing left from my side.
