### ISSUE TITLE
[Feature request] Add option to change font

### ISSUE THREAD

**Issue by Roshan-R** [gi-lom/dialect#138]
Awesome application!
Would be great if there was an option to change the font for the text area since it will improve accessibility.
I've already made some progress in my fork and would love to make a PR if it's good enough.

**Comment by fushinari** [comment]
Before I say anything else, really cool to see potential contributors from my state :smile:

May I ask what you mean by improving accessibility? How does changing the font to be different from the system-wide setting make it more accessible?

**Comment by fushinari** [comment]
Sorry, I just saw your code, tested it and I believe this feature is not within the scope of Dialect.

Thank you for your suggestion and your work in implementing the feature. It's very much appreciated but sadly, I don't think the feature belongs in Dialect.
