### ISSUE TITLE
Flatpak version: translate.astian.org is down. Can only use google translate

### ISSUE THREAD

**Issue by jbingram** [gi-lom/dialect#141]
Hi there
Flatpak version: translate.astian.org is down. Can only use google translate.
I want to use libretranslate, not google.
What are your suggestions please?
Cheers

**Comment by fushinari** [comment]
You can use the `libretranslate.com` instance for now. We can't make it the default instance because it's a testing instance so any suggestions for any other instances that we could set as the default is welcome.

**Comment by jbingram** [comment]
okidok, thx for your prompt reply. Much appreciated

**Comment by fushinari** [comment]
`translate.astian.org` is back up and is now running LibreTranslate 1.2 :tada: (which means server-side language detection and that we can drop the `langdetect` dependency since no known instances use older versions)
