### ISSUE TITLE
Using a local LibreTranslate server

### ISSUE THREAD

**Issue by ZER0-X** [gi-lom/dialect#144]
I can't use `localhost:5000` as a LibreTranslate instance, it give me a message saying that the it is not valid.

https://github.com/uav4geo/LibreTranslate

**Comment by fushinari** [comment]
You should be able to use `127.0.0.1:5000`. I had tested it before and it seemed to work.

**Comment by ZER0-X** [comment]
Did you use any special setting?

I am only using `libretranslate --offline` to start it.

**Comment by fushinari** [comment]
Hmm... I don't really remember. I'll try again and get back to you about it. This is an essential feature, so I'll get it working asap if it doesn't work already.

**Comment by fushinari** [comment]
The issue was that Dialect enforced https. While it's good behavior, it's not required for requests from localhost. So I've changed this behavior in 7310a25 . Thanks for letting me know about this issue, much appreciated :)
