### ISSUE TITLE
Show pronunciation in both sides

### ISSUE THREAD

**Issue by rafaelmardojai** [gi-lom/dialect#147]
Currently we only show pronunciation for the source lang. Google Translate shows pronunciation for both sides when available.

![Screenshot_2021-04-03 Traductor de Google](https://user-images.githubusercontent.com/6210397/113485606-1edf4d00-9474-11eb-9d5f-e6f8525e3a8f.png)

`extra_data` from py-googletrans also provides pronunciation for dest lang:
```
{'translation': [['あなたの良い友達', '你好，朋友', None, None, 11, None, None, [[]], [[['9588ca5d94759e1e85ee26c1b641b1e3', 'kgmt_en_ja_2020q3.md']]]], [None, None, 'Anata no yoi tomodachi', 'Nǐ hǎo, péngyǒu']], 'all-translations': None, 'original-language': 'zh-CN', 'possible-translations': [['你好，朋友', None, [['あなたの良い友達', 0, True, False], ['あなたの良い友人', 0, True, False]], [[0, 5]], '你好，朋友', 0, 0]], 'confidence': 1, 'possible-mistakes': None, 'language': [['zh-CN'], None, [1], ['zh-CN']], 'synonyms': None, 'definitions': None, 'examples': None, 'see-also': None}
```

Probably we should format the pronunciation and mistakes more beautifully in `translators.basetrans.Translation`, so this ugly formatting stays in `GTranslator`.

**Comment by fushinari** [comment]
> Probably we should format the pronunciation and mistakes more beautifully in translators.basetrans.Translation, so this ugly formatting stays in GTranslator.

Yeah, we should probably create a better structure for extra_data.

How about:

```python
{
    'possible-mistakes': '',
    'src_pronunciation': '',
    'dest_pronunciation': '',
}
```

for starters?

**Comment by rafaelmardojai** [comment]
> How about:
> 
> ```python
> {
>     'possible-mistakes': '',
>     'src_pronunciation': '',
>     'dest_pronunciation': '',
> }
> ```

Yeah, that looks good.
