### ISSUE TITLE
TTS audio should be downloaded and played asynchronously

### ISSUE THREAD

**Issue by KSXGitHub** [gi-lom/dialect#17]
## Problem

Currently, whenever user clicks the "speaker" button, the GUI freezes until audio is downloaded and played. This is a bad user experience.

## Suggestion

Use `async` and `await` to download and play audio.

**Expected behavior:**
* When user first clicks the "speaker" button, the button should change its icon to "stop" (as in "play"/"pause"/"stop") and the application should begin downloading audio file from Google.
* While audio is being downloaded or played, if user clicks the "stop" button, the downloading/playing process should be stopped, and the button should change its shape back to "speaker".
* When audio finishes, the "stop" button should change its icon to back to "speaker".

---

**P.S.** I am inexperience in Python so I can't help you with this, sorry :(

**Comment by rafaelmardojai** [comment]
Any call to Google Translator API should be asynchronous.

But we're going to have problems with GLib main loop, since PyGObject doesn't support Python asyncio event loop. 

The solution would be using [asyncio-glib](https://github.com/jhenstridge/asyncio-glib/) library.

**Comment by gi-lom** [comment]
I will look at the problem when it's morning here

**Comment by gi-lom** [comment]
Ok I've been trying all day and I cannot find a way to make async work between Gtk and the voice function.
EXPECTED RESULT: Voice button is pressed, voice from text-to-speech is downloaded and executed asychronously (UI does not freeze).
CURRENT RESULT: Voice button is pressed, voice function is executed only when window is closed and variable SecondLanguageVoice in UIVoicePlay function has value "zu".

How I edited the code:
[gnabel.tar.gz](https://github.com/gi-lom/gnabel/files/5071324/gnabel.tar.gz)
