### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by bertob** [gi-lom/dialect#29]
The current name is not great, the `g` prefix makes it look like an old app from the GNOME 2 days. Would you be open to changing it?

I have a blog post on the subject you might be interested in: https://blogs.gnome.org/tbernard/2019/04/26/naming-your-app

**Comment by gi-lom** [comment]
Ok. Will think of a new name and icon. If you have any suggestion, feel free to write here

**Comment by bertob** [comment]
A few ideas to get started with:

- polyglot
- paraphrase
- interpreter
- literal
- transpose

**Comment by gi-lom** [comment]
Not bad, but there are apps for Android with those names :( apart from paraphrase, but I preferred the others

**Comment by gi-lom** [comment]
I was starting to think of some word from a language different than English:
Glossa (Greek for "language")
Parola (Italian for "word")

**Comment by bertob** [comment]
Dialect sounds great!

**Comment by gi-lom** [comment]
@KSXGitHub , @rafaelmardojai , @fushinari , what do you think of the proposals?

**Comment by fushinari** [comment]
I like Dialect! Just sounds right for some reason.

**Comment by rafaelmardojai** [comment]
+1 For **Dialect**

**Comment by gi-lom** [comment]
Ok so guess Dialect will it be!

**Comment by rafaelmardojai** [comment]
We should also change `gi-lom` to `gi_lom` on the app ID.

[GtkApplication allows hyphen ("-")](https://developer.gnome.org/ChooseApplicationID/)  on the app ID but Flatpak doesn't. So GtkApplication will fail to register the D-Bus under Flatpak.

**Comment by gi-lom** [comment]
> We should also change `gi-lom` to `gi_lom` on the app ID.
> 
> [GtkApplication allows hyphen ("-")](https://developer.gnome.org/ChooseApplicationID/) on the app ID but Flatpak doesn't. So GtkApplication will fail to register the D-Bus under Flatpak.

Very well

**Comment by fushinari** [comment]
> We should also change `gi-lom` to `gi_lom` on the app ID.
> 
> [GtkApplication allows hyphen ("-")](https://developer.gnome.org/ChooseApplicationID/)  on the app ID but Flatpak doesn't. So GtkApplication will fail to register the D-Bus under Flatpak.

Oh wow, I didn't know this. In the initial commit for GtkApplication, I originally used `gi_lom` and then "corrected" it into `gi-lom` later...

**Comment by fushinari** [comment]
@gi-lom This can be now closed.
