### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by gi-lom** [gi-lom/dialect#31]
There could be a better icon more compliant with GNOME guidelines and more stylized.
If you have any suggestions, put them here

Common themes:
- A globe
- A latin and a Japanese letter
- A book
- A speech bubble

**Comment by bertob** [comment]
What about the one @jimmac proposed here? https://github.com/gi-lom/gnabel/issues/25#issuecomment-673411541

Personally I think that would work well, though I'd maybe change the colors a little bit to make it more unique.

**Comment by gi-lom** [comment]
A bit too vanilla, but immediately recognizable. The thing that worries me is the fact it's identicaly to the Google Translate icon

**Comment by fushinari** [comment]
Now that the rewrite is complete, bar maybe some unexpected bugs we don't yet know about ofc, this should be the next immediate focus. The icon proposed in #25 was great but shows its roots a bit too much. The icon itself is great but the colors are too similar to Google Translate.

**Comment by jimmac** [comment]
Some color variants for consideration:

![image](https://user-images.githubusercontent.com/14821/95855466-c0ed6a80-0d58-11eb-920e-5f6e9844a446.png)
![image](https://user-images.githubusercontent.com/14821/95855624-fc883480-0d58-11eb-8faa-15d2c87ec12c.png)
![image](https://user-images.githubusercontent.com/14821/95855755-30635a00-0d59-11eb-8d3a-e140f2eb38a9.png)

**Comment by fushinari** [comment]
They look amazing! I'm a bit conflicted because I like all three of them... How would they look like with a slight tint on the japanese text bg? Maybe a red tint on the yellow version for example?

@rafaelmardojai thoughts?

**Comment by bertob** [comment]
I wonder if it'd make more sense if the letter up top was a D for dialect?

Color-wise my favorite is green, i think.

**Comment by fushinari** [comment]
> I wonder if it'd make more sense if the letter up top was a D for dialect?

Oh yes, like Google with their G. That makes a lot of sense.

**Comment by rafaelmardojai** [comment]
Yes, using a D for the latin letter makes more sense.

About the color, I personally like the purple one, the green also looks good.

**Comment by fushinari** [comment]
I too prefer the purple icon over green. Especially the "A" in it.

@jimmac could you do a variant of the purple icon with a "D" instead of the "A"?

**Comment by jimmac** [comment]
![image](https://user-images.githubusercontent.com/14821/95962968-5e9f7300-0e07-11eb-803d-eb0c8ce5d474.png)

I'll prepare a merge request if this is fine.

**Comment by fushinari** [comment]
> I'll prepare a merge request if this is fine.

Looks amazing! Please do!
