### ISSUE TITLE
libhandy UI

### ISSUE THREAD

**Issue by fushinari** [gi-lom/dialect#32]
We need mockups and ideas for implementation of a libhandy-based Mobile user interface. It has to be usable both on mobile and desktop and should not feel out of place in either environments.

**Comment by rafaelmardojai** [comment]
Some initial ideas. Just brain storming.

![dialect-mockup-v1](https://user-images.githubusercontent.com/6210397/90534086-f00fa300-e13e-11ea-8cdd-d3f6a9db60d0.png)

**Comment by rafaelmardojai** [comment]
Hey @bertob, if you have some free time we will love to see some ideas and feedback to make this app more HIG compliant and mobile friendly.

**Comment by fushinari** [comment]
I like these. Especially the first desktop mockup. Familiar yet pretty. Also, we could hide the bottom language buttons when the window becomes smaller.

The second one is also good but the position of the switch languages button feels odd.

The mobile UI seems nice and simple.

This is what I had in mind for the mobile GUI (edited to match your controls a little):
![Screenshot_20200819_003418](https://user-images.githubusercontent.com/28823274/90554666-d5c3dc80-e1b3-11ea-9a65-6feebfa57c90.png)

I have no idea how to do the nice frames seen in your mockups. :(  This is a dirty double GtkFrame.

**Comment by rafaelmardojai** [comment]
> The second one is also good but the position of the switch languages button feels odd.

Yeah, i had this option first:

![dialect-mockup-v1](https://user-images.githubusercontent.com/6210397/90555768-7f2bb380-e15d-11ea-8e0c-820942360e3a.png)

But I felt like it was a lot of buttons in the same row.

> This is what I had in mind for the mobile GUI (edited to match your controls a little):

Having the language switchers in the middle also looks good!

**Comment by fushinari** [comment]
> Yeah, i had this option first:
> But I felt like it was a lot of buttons in the same row.

Yeah, that looks odd in another way... Having the controls in the titlebar would work on desktop but I don't like the idea of the mobile UI being too different from the desktop UI.

Btw, how would you do the frames we see in your mockups, always been curious... CSS? Or is there some widget that I don't know about? I can do this much with Glade:
![Screenshot_20200819_010054](https://user-images.githubusercontent.com/28823274/90557012-7667cb80-e1b7-11ea-82a6-df63d4f100ba.png)

But I can't do those nice slightly rounded corners.

**Comment by rafaelmardojai** [comment]
We would need some CSS to implement it, but my current mockups are just SVG's with the help of Inkscape and https://gitlab.gnome.org/Teams/Design/mockup-resources

**Comment by fushinari** [comment]
Do we want both the UIs in the same glade file or should it be separate?

**Comment by rafaelmardojai** [comment]
> Do we want both the UIs in the same glade file or should it be separate?

Probably separated if the glade file becomes too long. 

We will probably put both views in a [HdySqueezer](https://gnome.pages.gitlab.gnome.org/libhandy/HdySqueezer.html).

**Comment by gi-lom** [comment]
I too prefer the first desktop mockup.
Would it be possible to insert the language shortcuts (the buttons that in the desktop app are in the bottom) also on the mobile app? There seems to be space on the first mockup

**Comment by bertob** [comment]
@rafaelmardojai what you have there looks good to me! I think both 1 and 2 could work structurally, though I'm not sure the row of language buttons is needed in 1, since they're a second place to do the same thing as the switchers in the headerbar.

**Comment by gi-lom** [comment]
Btw, does GTK support responsive design or two different build would be needed for desktop and mobile?

**Comment by bertob** [comment]
@gi-lom It's a bit different from responsive design on the web, but Libhandy has some widgets that allow you to do similar things, e.g. HdySqueezer allows changing things based on the available size.

**Comment by rafaelmardojai** [comment]
> though I'm not sure the row of language buttons is needed in 1, since they're a second place to do the same thing as the switchers in the headerbar.

@bertob those are quick access to the lastest used languages, do you think that are unnecessary?

**Comment by bertob** [comment]
I haven't done any real research into this, but I think the UI would feel more focused if there was a single place to set the language for each side. Perhaps it'd be good to collect some relevant art and see how other apps do this.

**Comment by rafaelmardojai** [comment]
# Relevant Art

## Google
Very similar to my second mockup.

![google1](https://user-images.githubusercontent.com/6210397/90990499-bb00b780-e567-11ea-84f1-90e773ee61d0.png)
![google2](https://user-images.githubusercontent.com/6210397/90990563-2b0f3d80-e568-11ea-83db-fe4d6fa8b9af.png)

![gtrans](https://user-images.githubusercontent.com/6210397/90990753-8f7ecc80-e569-11ea-8e1f-b315f1752a32.png)

## Yandex
![yandex1](https://user-images.githubusercontent.com/6210397/90990603-6873cb00-e568-11ea-9415-d2d689a833e5.png)
![yandex2](https://user-images.githubusercontent.com/6210397/90990602-66117100-e568-11ea-9412-e489a271cd77.png)

## DeepL
![deepl1](https://user-images.githubusercontent.com/6210397/90990626-85100300-e568-11ea-988c-39db586d185c.png)
![deepl2](https://user-images.githubusercontent.com/6210397/90990623-83ded600-e568-11ea-8ad9-a8b3e4d8175e.png)

**Comment by rafaelmardojai** [comment]
What about this?

![dialect-mockup-v2](https://user-images.githubusercontent.com/6210397/90990816-15027c80-e56a-11ea-8019-ec3dfc196d48.png)

Showing the recent languages on top of the selection popover.

**Comment by fushinari** [comment]
I think we also need the ability to search within the language selection popover.

**Comment by fushinari** [comment]
@gi-lom what do you think about the last mockup?

Also, any ideas for the mobile GUI?

**Comment by gi-lom** [comment]
> @gi-lom what do you think about the last mockup?
> 
> Also, any ideas for the mobile GUI?

It is very good, I too had the idea of putting the most used languages on top of the menu in the beginning
