### ISSUE TITLE
Use GSettings to store settings

### ISSUE THREAD

**Issue by rafaelmardojai** [gi-lom/dialect#36]
Using [GSettings](https://developer.gnome.org/gio/stable/GSettings.html) will be better than saving settings to our own json file.

If is fine, I will provide a PR latter.

**Comment by rafaelmardojai** [comment]
Should we save Translations/Languages every time a translation is run or on when the window window close? 

I'm asking because I don't know if we want to reduce the number of I/O operations.
The obvious downside is that the history will be lost if the window is closed in an unexpected way.

**Comment by fushinari** [comment]
The addition I/O overhead should be minor and it should be non-blocking since it's being run in a thread. But in the case of live translation, it might be better to not do so and save while exiting instead.
