### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by gi-lom** [gi-lom/dialect#38]
I had fun writing Dialect, but I discovered maintaining an app is not really my cup of tea considering all I'm doing now is merging pull requests :) so I think that for the project's sake a more active maintainer would be better. Any of you would lake to take care of it?

**Comment by fushinari** [comment]
You could add me and rafaelmardojai as collaborators I think. I'm fine with it. @rafaelmardojai what do you think?

**Comment by rafaelmardojai** [comment]
Yeah, you can add us both as collaborators. We will try to maintain the project rolling 😄

**Comment by fushinari** [comment]
Since I've been now made a collaborator, we can consider this issue to be solved. :)
