### ISSUE TITLE
Add preferences window

### ISSUE THREAD

**Issue by rafaelmardojai** [gi-lom/dialect#40]
What preferences will we want to expose? 

Some thoughts:

- Option to enable automatic translation as you type (with some warning about API abuse)
- Option to disable translation history?
- Button to clear translation history?

**Comment by fushinari** [comment]
I'm working on the Glade rewrite of the UI. It won't be exactly as in the mockups just yet and will only be the desktop mode for now but it will use libhandy, which means we can use HdyPreferencesWindow for the settings.

Since you're already working on #36 , adding the necessary gsettings keys will be all that's necessary.

**Comment by fushinari** [comment]
Necessary options:
- Dark Mode - Switch
- Clear History - Button
- Disable History (should also hide the history buttons instead of disabling them) - Switch
- Live Translation - Switch
- Switch between "Ctrl+Enter to Translate" or "Enter to Translate" - Radio or Combo.

We can add the rest as we go and find more necessities.

**Comment by rafaelmardojai** [comment]
> - Disable History (should also hide the history buttons instead of disabling them) - Switch

What if we just disable the history saving? So the history functionality can be used, but is not remembered.

**Comment by fushinari** [comment]
> What if we just disable the history saving? So the history functionality can be used, but is not remembered.

I think I like that. That's probably better.

**Comment by rafaelmardojai** [comment]
Some ideas:

![g2763](https://user-images.githubusercontent.com/6210397/94968265-38eca280-04c6-11eb-89a4-d4c7cd4bd9d8.png)

I still don't know how to integrate the **Clear History** button. Ideas?

**Comment by fushinari** [comment]
LGTM.

> I still don't know how to integrate the **Clear History** button. Ideas?

I think second mockup but with a trash icon and tooltip instead of label will suffice.

**Comment by rafaelmardojai** [comment]
Like this?

![path2432](https://user-images.githubusercontent.com/6210397/94981669-a8c85080-04f9-11eb-9961-73bccf898fe4.png)

**Comment by rafaelmardojai** [comment]
Or this? 😂
![path2432](https://user-images.githubusercontent.com/6210397/94981701-f80e8100-04f9-11eb-8768-e98d2233234e.png)

**Comment by fushinari** [comment]
> Or this? 😂
> ![path2432](https://user-images.githubusercontent.com/6210397/94981701-f80e8100-04f9-11eb-8768-e98d2233234e.png)
> 

Like this probably. Because we want the switches to be aligned. But yeah, it looks weirder than I expected 😂 What if it was a circular button?

**Comment by rafaelmardojai** [comment]
> Like this probably. Because we want the switches to be aligned. But yeah, it looks weirder than I expected joy What if it was a circular button?

![path2432](https://user-images.githubusercontent.com/6210397/94982805-3a888b80-0503-11eb-9010-acbb87c76cbb.png)

**Comment by fushinari** [comment]
Let's just kill history persistence. Much easier and more intuitive. :sweat_smile:

**Comment by rafaelmardojai** [comment]
Yeah, I'm fine with that. 😂

**Comment by rafaelmardojai** [comment]
Just adding for final reference:
![path2432](https://user-images.githubusercontent.com/6210397/95022566-c30b4700-063d-11eb-99dc-2a05533e7e55.png)

Should we disabled the **Translate Accel** option if **Live Translation** is enable right?

**Comment by fushinari** [comment]
Yes, we can make it so that the Translate Accel option is hidden if the Live Translation switch is enabled.

**Comment by fushinari** [comment]
@rafaelmardojai I've pushed a cleanup (a727ec510441cc551d9aeececbc4786005f0e1b9). So if you're working on something, please be sure to rebase.

I have a mostly ready basic UI for the initial version of the Glade rewrite, but I have exams right now, so it might be a few days until I can properly work on it. So, I'm attaching it [here](https://github.com/gi-lom/dialect/files/5324054/init.zip).

In the meantime, you could work on it and I could review. Or I'll just pick up where I left off in a few days. Anything's fine :)
