### ISSUE TITLE
Renaming the master branch

### ISSUE THREAD

**Issue by fushinari** [gi-lom/dialect#41]
GitHub and every other platform is moving towards better terminology. So, I think we should too.

https://github.com/github/renaming#later-this-year

The required change is simple: rename the branch "master2" into "main".

**Comment by rafaelmardojai** [comment]
LGTM.

**Comment by fushinari** [comment]
@gi-lom I lack the necessary permissions, so could you please set the new "main" branch as the default branch?

**Comment by gi-lom** [comment]
Done
