### ISSUE TITLE
Gstreamer issue :)

### ISSUE THREAD

**Issue by LyesSaadi** [gi-lom/dialect#46]
Hello :grinning:!

First of all, great app! (And WOW! GREAT rewrite !)

The story is... I wanted to package dialect for Fedora now that there's a stable release. But... I've unfortunately discovered a bug with Gstreamer...

```
$ dialect
Traceback (most recent call last):
  File "/usr/share/dialect/dialect/main.py", line 35, in do_activate
    self.window = DialectWindow(
  File "/usr/share/dialect/dialect/window.py", line 94, in __init__
    bus = self.player.get_bus()
AttributeError: 'NoneType' object has no attribute 'get_bus'
```

And then, no window appear. The program doesn't really crash either. But if I open another terminal and retype the command, while the other one is still running, I get this:
![image](https://user-images.githubusercontent.com/33597258/96152413-6f81de80-0f04-11eb-8423-a23604ed56cb.png)

I cannot translate anything. Nothing works.

I think what happens here is quite clear, `Gst.ElementFactory("playbin", "player")` fails and return none, and can't create the rest of the window. When I retype the command, it forces the window to show itself, even if it's still incomplete.

So I think that « maybe it is just some Gstreamer plugin missing, right »? Well, no. `gstreamer1-plugins-base` is installed and installing all Gstreamer-related package (except one random one because it's too heavy) doesn't change anything :/.

But then, something weird happens. If I try to do `sudo dialect`... It _works_! I mean, since I'm using Wayland I still has no sound, but, at least, it can translate! So this seems to be some kind of permission issues?

Btw, the Flatpak version works.

**Comment by fushinari** [comment]
> Gst.ElementFactory("playbin", "player")

Could you edit the code and confirm that this is exactly what's happening? I only used playbin because it seemed easier to work with (less code I mean). But maybe we should do a better implementation later on.

Glad to know that at least the flatpak works well. But then that points to a missing dependency. (gst-python? Probably not since import seems to have succeeded.)

**Comment by rafaelmardojai** [comment]
I have build Dialect from source in Fedora 32 and works as expected.

**Comment by LyesSaadi** [comment]
> I have build Dialect from source in Fedora 32 and works as expected.
Then it's a problem with my configuration, thanks for the information ! And sorry for any inconvenience. I will investigate that further.

> I have those gstreamer1 plugins installed:
All of them are already installed on my computer...

**Comment by LyesSaadi** [comment]
Umm... I'm not longer sure it's a configuration problem? I tested it through a container and it still doesn't work...

@rafaelmardojai, would you mind if you tried to install Dialect from these RPM packages if you're currently using Fedora: `https://lyessaadi.fedorapeople.org/dialect/dialect-1.0.0-1.fc33.noarch.rpm https://lyessaadi.fedorapeople.org/dialect/python3-googletrans-3.0.0-1.fc33.noarch.rpm`? Then launching it from `/usr/bin/dialect`? If you're installation of Dialect is system-wide, this will crush it though :/!

**Comment by fushinari** [comment]
> Umm... I'm not longer sure it's a configuration problem? I tested it through a container and it still doesn't work...

I think the reason he was unable to reproduce it was because he tried it on a Fedora 32 setup and not 33. I don't have a Fedora 33 setup either, so sadly I can't test it.

**Comment by fushinari** [comment]
Let's close this only when we get proper confirmation.

**Comment by LyesSaadi** [comment]
Ok... This definitely makes no sense... Dialect work well when installing it from source in /usr/local, but not from RPM in /usr...

**Comment by rafaelmardojai** [comment]
I got this errors:
```
  - nothing provides python(abi) = 3.9 needed by python3-googletrans-3.0.0-1.fc33.noarch
  - nothing provides python3-httpx needed by python3-googletrans-3.0.0-1.fc33.noarch
```
```
  - conflicting requests
  - nothing provides python(abi) = 3.9 needed by python3-googletrans-3.0.0-1.fc33.noarch
  - nothing provides python3-httpx needed by python3-googletrans-3.0.0-1.fc33.noarch
```

Something to do with Fedora 33.

**Comment by LyesSaadi** [comment]
Yeah, this seems to be a problem with the RPM I created? Installing it from source in /usr works as well... This seems to be a Fedora-RPM related issue, since my specfile is quite ordinary...

**Comment by fushinari** [comment]
@rafaelmardojai Any reasons for defaulting to /usr/local as installprefix? Doesn't look like a good default

**Comment by LyesSaadi** [comment]
I can confirm that this is a problem with what Fedora uses to build and install meson projects. Something in the RPM macros is making the app not work.

To explain what I mean, Fedora packagers _generally_ do not use directly instructions that upstream provides to build a software. For example, if a software asks to build it software like this:

```bash
meson builddir --prefix=/usr/local
sudo ninja -C builddir install
```

Fedora packagers will do this:
```spec
# In the build section:
%meson
%meson_build

# In the install section:
%meson_install
```

This is for several security, optimization and standardization reasons. But all those are what we call macros, which are a quick way to type:
```bash
# %meson    
  CFLAGS="${CFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection}" ; export CFLAGS ; 
  CXXFLAGS="${CXXFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection}" ; export CXXFLAGS ; 
  FFLAGS="${FFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -I/usr/lib64/gfortran/modules}" ; export FFLAGS ; 
  FCFLAGS="${FCFLAGS:--O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -I/usr/lib64/gfortran/modules}" ; export FCFLAGS ; 
  LDFLAGS="${LDFLAGS:--Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld }" ; export LDFLAGS ; 
  LT_SYS_LIBRARY_PATH="${LT_SYS_LIBRARY_PATH:-/usr/lib64:}" ; export LT_SYS_LIBRARY_PATH ; 
  CC="${CC:-gcc}" ; export CC ; 
  CXX="${CXX:-g++}" ; export CXX 
    /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . x86_64-redhat-linux-gnu

# %meson_build
    /usr/bin/meson compile -C x86_64-redhat-linux-gnu -j 8 --verbose

# %meson_install
    DESTDIR=%{buildroot} /usr/bin/meson install -C x86_64-redhat-linux-gnu --no-rebuild
```

**SOMETHING** there causes the thing to fail... Why? I honestly have no clue...

**Comment by rafaelmardojai** [comment]
> Any reasons for defaulting to /usr/local as installprefix? Doesn't look like a good default

That was the default in the GNOME Builder template time ago when I started in GTK app devel. So I become use to that 😂.
But yes, looks like installing to `usr` is the normal.

**Comment by fushinari** [comment]
> To explain what I mean, Fedora packagers _generally_ do not use directly instructions that upstream provides to build a software. For example, if a software asks to build it software like this:

Ah, so it's like `arch-meson` on Arch. It doesn't fail on Arch, so maybe we should check out the differences between them. I've only seen it before when trying to put `komikku` on the OBS using you and Artem's specfile during my short Tumbleweed adventure.

**Comment by LyesSaadi** [comment]
> @rafaelmardojai Any reasons for defaulting to /usr/local as installprefix? Doesn't look like a good default

That's a good default IMO. `/usr` for most distributions is where they install apps. `/usr/local` in the other hand is where users install apps outside of the scope distributions and package managers.

**Comment by fushinari** [comment]
> That's a good default IMO. `/usr` for most distributions is where they install apps. `/usr/local` in the other hand is where users install apps outside of the scope distributions and package managers.

Oooh, then I guess that's something to keep. Thanks for letting me know

**Comment by rafaelmardojai** [comment]
Also looks like meson installs to `/usr/local` by default.

**Comment by LyesSaadi** [comment]
> Ah, so it's like `arch-meson` on Arch. It doesn't fail on Arch, so maybe we should check out the differences between them. I've only seen it before when trying to put `komikku` on the OBS using you and Artem's specfile during my short Tumbleweed adventure.

Did it work/fail? I don't know if OpenSUSE's meson provides those macros :stuck_out_tongue:!

**Comment by fushinari** [comment]
```
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /usr/bin/arch-meson
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ #!/bin/bash -ex
   2   │ # Highly opinionated wrapper for Arch Linux packaging
   3   │ 
   4   │ exec meson setup \
   5   │   --prefix        /usr \
   6   │   --libexecdir    lib \
   7   │   --sbindir       bin \
   8   │   --buildtype     plain \
   9   │   --auto-features enabled \
  10   │   --wrap-mode     nodownload \
  11   │   -D              b_lto=true \
  12   │   -D              b_pie=true \
  13   │   "$@"
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```
That's literally it.

**Comment by fushinari** [comment]
> Did it work/fail? I don't know if OpenSUSE's meson provides those macros stuck_out_tongue!

I think it worked. It simply didn't give me a final package. Probably because Komikku is technically piracy.

**Comment by fushinari** [comment]
@LyesSaadi Have you tried to see what happens when directly calling meson?

**Comment by LyesSaadi** [comment]
> @LyesSaadi Have you tried to see what happens when directly calling meson?
Yep, that's how I found out about this...

Now, what is weirder, when switching back to RPM with its macros... It works?

After some thinking, maybe is this a Gstreamer issue? Something happened in my computer which made Gstreamer randomly refuse to create a playbin? This. Is. Really weird!

I am trying again in a new container.

**Comment by fushinari** [comment]
> It works?

Lol, sorry but I'm laughing here. XD It's just so bizarre. But yeah, can relate. When you're about to post your findings about a particular bug online, the bug will suddenly become impossible to reproduce for some reason.

> After some thinking, maybe is this a Gstreamer issue after all? Something happened in my computer which made Gstreamer randomly refuse to create a playbin? This. Is. Really weird!

Something in your environment is probably making it choke. Have you tried anything else that makes use of gstreamer?

**Comment by LyesSaadi** [comment]
> Lol, sorry but I'm laughing here.

Personally, I laughed when seeing arch-meson :3.

> Something in your environment is probably making it choke. Have you tried anything else that makes use of gstreamer?

Does Firefox use Gstreamer? I've been listening to music/watching videos while waiting it to build? I just tried "Gnome Videos" right now and it works as expected.

> Probably because Komikku is technically piracy.

Let's just say... It's a simple Internet image viewer for some _really_ specific websites :stuck_out_tongue:.

**Comment by LyesSaadi** [comment]
Okay... I can confirm the issue _just_ disappeared... This is then 100% a Gstreamer issue, and the macros just a coincidence when trying things with the issue just disappearing at the same time.

Aaargh..... Sorry for all the wasted time and effort. Anyway, thank you really for the help! I will now proceed to package dialect for COPR and then for the official Fedora repos (why not EPEL if some want it for CentOS/RHEL)...

Damn it Gstreamer! Honestly, I already tried developing an app with that framework and I abandoned it because of all the obscurity behind it... (Only temporarily abandoning it, I'm just waiting for GTK4 to come out with its Video Widget :tada:!)

**Comment by fushinari** [comment]
> Personally, I laughed when seeing arch-meson :3.

I did too. I mean, "Highly opinionated" but like 10 lines? Not much of an opinion then, is it? :laughing:

> Does Firefox use Gstreamer? I've been listening to music/watching videos while waiting it to build? I just tried "Gnome Videos" right now and it works as expected.

Then it's the playbin object specifically? That's weird... I did say a better implementation could be possible but the current implementation should definitely still be working...

> Let's just say... It's a simple Internet image viewer for some _really_ specific websites stuck_out_tongue.

Well, that's what I like to think of it as myself. :new_moon_with_face: But looks like not the openSUSE devs. They're pretty specific about what software goes into their repos or is served from their servers (including the OBS). So sadly, I couldn't get it to work. One of the many minor reasons I left Tumbleweed. (There were bigger reasons too ofc.)

**Comment by fushinari** [comment]
No worries, at least it's solved for now. Let's look forward to someone else encountering the same issue. :rofl:

**Comment by LyesSaadi** [comment]
Dialect is now on COPR :tada:! For now it is only for Fedora 33 and rawhide, but tomorrow I would be able to add Fedora 32 to the list, as soon as [this update](https://bodhi.fedoraproject.org/updates/FEDORA-2020-c4bb3d51f1) is pushed to stable!

https://copr.fedorainfracloud.org/coprs/lyessaadi/dialect/

I will wait tomorrow to submit it for review to Fedora's official repos as I have some issues with python-googletrans to deal with before.

For the curious, [here is the specfile](https://gitlab.com/LyesSaadi/spec/-/blob/master/dialect/dialect.spec)

**Comment by LyesSaadi** [comment]
I still am unable to package dialect for Fedora 32 because of some dependency problems...

Anyway, the package was submitted for review: https://bugzilla.redhat.com/show_bug.cgi?id=1889105

**Comment by fushinari** [comment]
@LyesSaadi Is Dialect now up on Fedora repos? [This](https://src.fedoraproject.org/rpms/dialect) is it right?

**Comment by LyesSaadi** [comment]
Yes it is :D ! But, it is only in "testing" for now ! [This is the update !](https://bodhi.fedoraproject.org/updates/FEDORA-2020-c469542619) So, it will hit stable in 3 days ;).

**Comment by fushinari** [comment]
That's awesome! And almost in time for 1.1.0 too!
