### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by musicsd** [gi-lom/dialect#50]
"Do not translate the program name".
 why?

**Comment by rafaelmardojai** [comment]
I was the one that put that there by personal taste.

But if the other Dialect contributors are fine about translating the app name, I don't have hard feelings about it.

**Comment by fushinari** [comment]
Because a name is a name and must never be translated. Even though Dialect is an English word, it is also the name of the application and should remain constant.

As a technical reason, the name is fixed everywhere else (used either as `dialect` or as `com.github.gi_lom.dialect`), so it'd be odd to only be different in the desktop file.

**Comment by meskobalazs** [comment]
Just adding my two cents. Keeping the original names of the applications is usually a good idea. There are exceptions however, for example GNOME apps (or default apps of other DEs), these usually have their "code names" and their GNOME app name. E.g. Totem is also known as GNOME Videos, and we translate the latter, but not the former. Dialect doesn't call itself GNOME Dialect so I am not inclined to translate its name – and I didn't. However if it would call itself GNOME Dialect, I would recommend "keeping in line".

**Comment by rafaelmardojai** [comment]
> Just adding my two cents. Keeping the original names of the applications is usually a good idea. There are exceptions however, for example GNOME apps (or default apps of other DEs), these usually have their "code names" and their GNOME app name. E.g. Totem is also known as GNOME Videos, and we translate the latter, but not the former. Dialect doesn't call itself GNOME Dialect so I am not inclined to translate its name – and I didn't. However if it would call itself GNOME Dialect, I would recommend allowing translations.

Yeah, also in that case it will got a more generic name like GNOME Translate.

**Comment by fushinari** [comment]
Since we're all in agreement, let's close the issue. :)

**Comment by musicsd** [comment]
😐😑

**Comment by musicsd** [comment]
Now I want to translate the program into Persian, write the name in Persian or the same in English?

**Comment by rafaelmardojai** [comment]
Write a "Persianised" version of "Dialect", or whatever you would do to transliterate any foreign brand to Persian.

**Comment by rafaelmardojai** [comment]
Or how would you write "GNOME" in Persian?

**Comment by musicsd** [comment]
I understand ... I write the same name in Persian. Thank you
