### ISSUE TITLE
"Did you mean" suggestion when misspelled text

### ISSUE THREAD

**Issue by TomaszGasior** [gi-lom/dialect#55]
UX would be much better and more comparable with web Google Translate interface, when you app would be able to provide "Did you mean" suggestions when text has wrong, misspelled words. I don't know whether API provides this information but IMHO without this kind of suggestion for end users the app has little sense for me.

![Zrzut ekranu z 2020-10-17 15-21-14](https://user-images.githubusercontent.com/1395027/96338221-ca464200-108c-11eb-86a7-2d486e5e368b.png)

**Comment by fushinari** [comment]
I'd have liked to have this too, but unfortunately, it looks like the API doesn't provide this feature.
