### ISSUE TITLE
Translation into recent languages in overview (Search provider)

### ISSUE THREAD

**Issue by nexeleriot** [gi-lom/dialect#56]
This would be a good feature. I started making it in my fork and I've got progress

![Снимок экрана от 2020-10-17 22-49-53](https://user-images.githubusercontent.com/70663363/96352451-e3221800-10cb-11eb-8ad1-0b2b83750f15.png)

**Comment by nexeleriot** [comment]
I didn't add it to meson yet (because i have never used it before). I used a script to install it

**Comment by fushinari** [comment]
That's an amazing idea! It definitely has to be optional due to concerns like API abuse just like Live Translation, unnecessary bandwidth usage, privacy by default, etc but yes, seems very useful! I have something similar in my KRunner (based on Dialect's translation code, but with source language always on auto and destination language always on English) and it does come in handy. So I'd be interested in a PR.

**Comment by nexeleriot** [comment]
I think I'll add some more features and make a PR tomorrow  👍

**Comment by rafaelmardojai** [comment]
Awesome!

> It definitely has to be optional due to concerns like API abuse just like Live Translation, unnecessary bandwidth usage, privacy by default, etc

I think GNOME disable by default new apps search providers.

**Comment by fushinari** [comment]
> I think GNOME disable by default new apps search providers.

Really? I think I remember Lollypop's search as being enabled by default. Maybe I'm just misremembering though.

**Comment by nexeleriot** [comment]
No, they are enabled by default. Maybe we can disable dialect provider using gsettings in postinstall script

**Comment by rafaelmardojai** [comment]
For some reason are disabled by default for me. 😂

**Comment by fushinari** [comment]
> No, they are enabled by default. Maybe we can disable dialect provider using Gio.Settings in postinstall script

Is there a way to give an option within the UI?

**Comment by nexeleriot** [comment]
> Is there a way to give an option within the UI?
Yes, using the same Gio.Settings

**Comment by nexeleriot** [comment]
Yes, using the same Gio.Settings

**Comment by nexeleriot** [comment]
Ok, I added it to meson and had written some scripts to disable it by default. Should I make a PR now (and should I leave it in separate branch or merge it to main for PR)?

**Comment by rafaelmardojai** [comment]
You can  leave it in a separate branch and make the PR against `main`.
