### ISSUE TITLE
Missing icon and name in top bar

### ISSUE THREAD

**Issue by bertob** [gi-lom/dialect#57]
The name and app icon are not being displayed in the top bar:

![image](https://user-images.githubusercontent.com/1908896/96365950-9a5a7580-1144-11eb-8c31-1620b0d35aa2.png)

**Comment by rafaelmardojai** [comment]
I can't reproduce the issue. Building from source neither installing from Flathub.

**Comment by bertob** [comment]
Huh, that's odd. Seems like it only happens when I start it from within [gnome-store](https://gitlab.gnome.org/haecker-felix/gnome-store) running within Builder. Probably some kind of sandbox limitation?

**Comment by fushinari** [comment]
> Huh, that's odd. Seems like it only happens when I start it from within [gnome-store](https://gitlab.gnome.org/haecker-felix/gnome-store) running within Builder. Probably some kind of sandbox limitation?

Do other applications work fine?

**Comment by rafaelmardojai** [comment]
I have tried running `flatpak-spawn --host flatpak run com.github.gi_lom.dialect` from a sandboxed app running within Builder and worked as expected.

**Comment by A6GibKm** [comment]
Could not reproduce in Silverblue 33. I launched the app from gnome-store, which was running from gnome-builder.

**Comment by bertob** [comment]
Seems like it's something weird about my system in particular then, feel free to close :)

**Comment by BrainBlasted** [comment]
This can happen when the install finished before the system fully finishes registering the flatpak. Same thing happens with gnome-software.
