### ISSUE TITLE
Question for meaning of one settings (regarding dialect.pot)

### ISSUE THREAD

**Issue by Etamuk** [gi-lom/dialect#58]
Hello!

I am working on the German translation of dialect and finished it 99%. :-) 
But one thing I cannot understand.
String: "The opposite accel will be used for new line."  I know what this is doing but I am confused about the word "opposite". Does that mean the live translation starts to work with the new input? So could it be "The live translation will be start with a new line."? 

Kind regards

**Comment by rafaelmardojai** [comment]
Translation Accel is about the keyboard accelerator/shortcut to run the translation if Live Translation is disabled.

"The opposite accel will be used for new line." means that if you selected "Enter" as accel, "Ctrl + Entrer" will be used to add a new line.

I'm not native English speaker, so probably that line can be improved.

**Comment by Etamuk** [comment]
Thank you for clarifying this. 
I think I found a good translation for it. 
Kind regards.
