### ISSUE TITLE
Speach keeps playing after closing the app

### ISSUE THREAD

**Issue by Kekun** [gi-lom/dialect#62]
I translated a really long text, clicked the Listen button, closed the app, the speach kept playing in the background and I had to kill the app.

**Comment by rafaelmardojai** [comment]
You closed the app when the TTS was loading right?

**Comment by fushinari** [comment]
Yeah, they were originally daemon threads but I'd reverted that because it was an unclean end and tbh, I didn't really understand how daemon threads worked either. But now, I've reverted to the old behavior. Should be fine, but can you test just in case?

**Comment by Kekun** [comment]
It was when closing the app after the playback started, but I can't trigger that issue anymore, thansk! :)
