### ISSUE TITLE
Change the hiragana letter on app icon

### ISSUE THREAD

**Issue by ekickx** [gi-lom/dialect#66]
I find the Japanese letter on the icon a bit weird. So `あ` is pronounced `a` and  `ぢ` can be pronounced `ji`, `zi`, or `di`. Since `dialect` is a translator app, I think it more makes sense to translate `D` into `ぢ` instead of `あ`.

**Comment by ekickx** [comment]
Actually I don't know whether to just comment on old issue or opening new one. But since #31 is already fixed by #44, I think I should open new issue. Sorry if I'm doing it wrong, I'm not used with opening an issue 😅😅

**Comment by fushinari** [comment]
I see. That makes sense.

@jimmac is it possible to address this issue?
