### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by musicsd** [gi-lom/dialect#69]
I'm sorry, I have been translating this program for almost two weeks, but I do not understand these three sentences to complete the translation. What are these?

`Warning: You could get your IP banned by API abuse.`

`Translate Accel`

`The opposite accel will be used for new line.`

**Comment by musicsd** [comment]
`Warning: You could get your IP banned by API abuse.`

Warns about swearing, but if this warning is not heeded, the ip will be blocked.
It is true?

**Comment by rafaelmardojai** [comment]
> `Warning: You could get your IP banned by API abuse.`
> 
> Warns about swearing, but if this warning is not heeded, the ip will be blocked.
> It is true?

It's a warning about enabling the Live Translation preference. It's virtually posible that your IP will get a banned by too many requests to the server.

**Comment by rafaelmardojai** [comment]
> `Translate Accel`
> 
> `The opposite accel will be used for new

About this, you can see #58.

**Comment by musicsd** [comment]
Thank you very much
