### ISSUE TITLE
Update translations for 1.1.0

### ISSUE THREAD

**Issue by rafaelmardojai** [gi-lom/dialect#75]
`1.1.0` will be released soon. We have added a few new strings and slightly changed others.

CC: @Etamuk, @musicsd, @meskobalazs, @albanobattistella, @nexeleriot, @v30xy.

Thanks in advance!

**Comment by fushinari** [comment]
The "Translated by" should probably be hidden if the language is English, but then the order of strings in `window.py` would change again.

**Comment by rafaelmardojai** [comment]
> but then the order of strings in window.py would change again. (i.e. if we add code to hide it if the user is still on English.)

No really a problem, meson/ninja do the work of update the pot/po files with code changes by running `ninja dialect-update-po` after building.

> I think it's better to just have a list of translators with the languages in brackets.

The `<property name="translator-credits">translation-credits</property>` is widely used in GNOME apps, and I havent seen such mechanism to hide it when language is English.

**Comment by fushinari** [comment]
Sorry, I edited a second too late. As I edited above, there's a bug where the About dialog says "Translated by: translation-credits" in the About dialog. There's a similar bug in Blanket where it says "translator1, translator2, ..." instead.

**Comment by rafaelmardojai** [comment]
> Sorry, I edited a second too late. As I edited above, there's a bug where the About dialog says "Translated by: translation-credits" in the About dialog. There's a similar bug in Blanket where it says "translator1, translator2, ..." instead.

Yeah, I now that. Lollypop does the same

**Comment by fushinari** [comment]
So we just keep the bug?

**Comment by rafaelmardojai** [comment]
Just found the real bug, if you set it to `translator-credits` instead of `translation-credits` GTK hides it automatically.

**Comment by fushinari** [comment]
Wow, that is so neat! Really must appreciate how much effort the GNOME devs have put into stuff like this. If any of you are reading this, thanks a lot, you folks are amazing!

**Comment by v30xy** [comment]
Hello. Although I am not using linux yet, I will continue to translate. I am sorry that I cannot discover the problems that may occur for Turkish.

**Comment by fushinari** [comment]
You're contributing even though you're not yet using Linux? That's amazing! Thanks for your work.

You don't have to worry much about problems, they don't generally occur with translations. Problems are usually something we create, not translators. :laughing:

**Comment by fushinari** [comment]
I think we're done?

**Comment by Etamuk** [comment]
> I think we're done?

:heavy_check_mark: German translation for 1.1.0 is ready :-)

**Comment by rafaelmardojai** [comment]
Yeah, all translations are ready.

**Comment by fushinari** [comment]
Okay, I'll make a release then

**Comment by rafaelmardojai** [comment]
> Okay, I'll make a release then
Wait.

**Comment by fushinari** [comment]
Okay

**Comment by rafaelmardojai** [comment]
Check out #88. 

I'm losing this since translations are done.
