### ISSUE TITLE
Search Provider doesn't work in Flatpak

### ISSUE THREAD

**Issue by rafaelmardojai** [gi-lom/dialect#88]
Currently I don't have time to checkout this, but just noticed after installing exported `.flatpak` from GNOME builder.

I don't know if we need to own `com.github.gi_lom.dialect.SearchProvider` in the manifest, or if it's another issue.

**Comment by fushinari** [comment]
I see. Do we have any examples of apps whose search providers do work from flatpaks?

**Comment by rafaelmardojai** [comment]
> I see. Do we have any examples of apps whose search providers do work from flatpaks?

I have Lollypop and Icon Library installed from flathub with search providers working fine.

**Comment by fushinari** [comment]
Okay, I'll look into it asap

**Comment by fushinari** [comment]
We have a power outage here, so I can't look into this for now. Hopefully tomorrow morning or later today (it's already 10:20 pm here though).

But I did notice that Icon Library's flatpak owns the name `org.gnome.design.IconLibrary.SearchProvider`. So I've pushed that change. So, could you test it?

**Comment by fushinari** [comment]
I did fix it earlier. I just didn't have it enabled...

**Comment by fushinari** [comment]
So, 1.1.0?

**Comment by fushinari** [comment]
I had the metainfo changelog ready but I'm going  to sleep (I badly need it :sweat_smile: ). So, if after testing, everything works as expected, go ahead with the release. If you end up not getting the time to, I'll do it tomorrow, so no worries.
```xml
    <release version="1.1.0" date="2020-10-30">
      <description>
        <ul>
          <li>Added a search provider for GNOME</li>
          <li>Added support for "Did you mean" suggestions</li>
          <li>Added a Ctrl+Q shortcut to quit</li>
          <li>Added Hungarian translation</li>
          <li>Added Italian translation</li>
          <li>Added Persian translation</li>
          <li>Added Russian translation</li>
          <li>Added Turkish translation</li>
          <li>Fixed some issues with the icon</li>
          <li>Fixed several bugs</li>
          <li>Made some minor UI improvements</li>
        </ul>
      </description>
    </release>
```

**Comment by rafaelmardojai** [comment]
The permission to `ca.desrt.dconf` didn't let me change Dialect preferences. So Live Translation was always disabled, removing the permission with Flatseal solved the issue for me.

Looks like `--talk-name=ca.desrt.dconf`  also needs `--env=DCONF_USER_CONFIG_DIR=.config/dconf` to work. But it only allows you to save GSettings in the host, so no really needed. 

Probably the issue was that I had Live Translation disabled for some confusion in my side. So I think that `com.github.gi_lom.dialect.SearchProvider` permission is the only thing we need.

**Comment by fushinari** [comment]
It works... Why didn't it work the first time for me then? Weird... Flatpak is weird :laughing: 

Well, either way, I'm just glad that it works now.

**Comment by pesader** [comment]
Hi! Sorry to revive this issue but I haven't been able to get the search provider working on the Flatpak version of Dialect as well.

Is there some additional tweaking (Dialect's prefereces, Flatpak permissions, etc) I need to do in order to get it working? Or is there some specific syntax I need to use in the search query (e.g. "hola in English" or "ciao in EN")?

Thank you for developing this awesome app!

**Comment by rafaelmardojai** [comment]
> Hi! Sorry to revive this issue but I haven't been able to get the search provider working on the Flatpak version of Dialect as well.
> 
> Is there some additional tweaking (Dialect's prefereces, Flatpak permissions, etc) I need to do in order to get it working? Or is there some specific syntax I need to use in the search query (e.g. "hola in English" or "ciao in EN")?
> 
> Thank you for developing this awesome app!

You need live translation enabled in Dialect's preferences, and the search provider in GNOME Settings search panel.

**Comment by Ridhubharan** [comment]
The search provider is not working. I have installed Dialect from Flathub, enabled live translation and search in Gnome settings. But still the search is not working.
I am using Fedora 36.

**Comment by rafaelmardojai** [comment]
> The search provider is not working. I have installed Dialect from Flathub, enabled live translation and search in Gnome settings. But still the search is not working.

Yup, we recently noticed that the SP in the stable version `1.4.1` is broken when working in the new version.

All is fixed in `main`, and the new version should come out soon.

**Comment by Ridhubharan** [comment]
> All is fixed in main, and the new version should come out soon.
That's awesome.
Quick question, will the search provider give results in only one language or is there an option to get translation from different languages?
